### ISSUE TITLE
Error in fread

### ISSUE THREAD

**Issue by dnimish85** [Westat-Transportation/summarizeNHTS#3] opened 2018-02-26 19:24 UTC
Hi Anthony, Alex,

I am trying to use read_data function of summerizeNHTS. But it is giving me following error - 

Error in fread(input = file.path(self$path, table_csv), select = c(table_key,  : 
  File 'C:/Data/R/Project_Test_1/R_test_1/csv/2017/person_weights.csv' does not exist. Include one or more spaces to consider the input a system command.

When I change the name of the file in csv folder to person_weights.csv, it gives me a different error - 

Error in fread(input = file.path(self$path, table_csv), select = c(table_key,  : 
  Column name 'HOUSEID' in colClasses[[1]] not found

Is your read_data function has something hard coded in it or why I am getting these errors? 

Thank you,
Nimish

**Comment by AnthonyFucci** [comment] 2018-02-26 20:31
Nimish, based on this description, I think you are missing the step from tutorial 0 where you need to tell summarizeNHTS to configure your NHTS dataset as an NHTS add-on dataset. This only needs to be done once. You may want to restore your original file names or files for sanity before running the following line in a new R session:

```R
library(summarizeNHTS)
prepare_add_on_files(
  directory = "C:/Data/R/Project_Test_1/R_test_1/csv/2017/",
  weight_type = "5day"
)
```

This function call will make a some updates to your weight data csv files, so please keep your original copies somewhere else.

**Comment by dnimish85** [comment] 2018-02-27 15:48
Thanks Anthony. 

I guess I had used it but with wrong syntax so it did not prepare my files the way it needed. 

I also renamed some of the files as it did not understand  numbers in the file names such as  _"household 022018.csv"_

**Comment by dnimish85** [comment] 2018-03-06 16:24
Hi Anthony, 

I guess I am doing something wrong again. First of all I could prepare the files and I can see the summary of the nhts_data. I guess that means csv files are linked to the Nhts_data. Now when I try to use 
summarize_data(
  data = nhts_data,
  agg = 'household_count'
)

I get results as the data summary. But when I try to use - 
summarize_data(
  data = nhts_data,
  agg = 'person_count'
)
I get following error: 
Error in `[.data.table`(data_table, , lapply(.SD, sum), by = by, .SDcols = weight_names) : 
  column or expression 1 of 'by' or 'keyby' is type NULL. Do not quote column names. Usage: DT[,sum(colC),by=list(colA,month(colB))]

I think there is problem only in the person_count field or input of the value. Because even if I try to use something else related to person it is giving error. 

Thanks.

**Comment by AnthonyFucci** [comment] 2018-03-07 17:52
Hi Nimish, I was able to run the 'person_count' query using INCOG's dataset. I set up the data files in a new directory and ran the following with success.
```r
library(summarizeNHTS)

prepare_add_on_files(
  directory = "C:/NHTS/INCOG/csv/2017",
  weight_type = "5day"
)

nhts_data <- read_data(
  dataset = "2017",
  csv_path = "C:/NHTS/INCOG"
)

summarize_data(
  data = nhts_data,
  agg = 'person_count'
)
```

If you still reproduce the error from before, can you provide the output of the following code in a text file to help troubleshoot further? Run this code in the same session as the error when you receive it.
```r
str(nhts_data)
getwd()
lapply(nhts_data$weights, colnames)
lapply(nhts_data$data, colnames)
sessionInfo()
```

Thanks!

**Comment by dnimish85** [comment] 2018-03-07 18:57
It worked now. I am not sure what was happening. I will close this issue. 

Thanks!

**Comment by dnimish85** [comment] 2018-03-07 20:37
Well, I started in the new folder and I can reproduce the error. I run that code and here is the output: 

> str(nhts_data)
Classes 'HTS.data', 'R6' <HTS.data>
  Public:
    clone: function (deep = FALSE) 
    data: list
    dataset: 2017
    initialize: function (dataset = NULL, select = NULL, path = NULL) 
    path: C:/Data/R/Project_Test_1/R_test_2/csv/2017
    print: function (...) 
    read_all: function () 
    select: AGERANGE AIRPORT ALT_1 ALT_2 ALT_3 ALT_4 ALT_5 ALT_6 ALT ...
    weights: list
  Private:
    path_check: function () 
    read_data: function (table_name) 
    read_weights: function (table_name) 
    table_variables: function (table_name) 
    variable_classes: function (table_name) 
    variable_lookup: function ()  
> getwd()
[1] "C:/Data/R/Project_Test_1/R_test_2"
> lapply(nhts_data$weights, colnames)
$household
  [1] "HOUSEID"   "WTHHFIN"   "WTHHFIN1"  "WTHHFIN2"  "WTHHFIN3"  "WTHHFIN4"  "WTHHFIN5"  "WTHHFIN6"  "WTHHFIN7"  "WTHHFIN8"  "WTHHFIN9"  "WTHHFIN10"
 [13] "WTHHFIN11" "WTHHFIN12" "WTHHFIN13" "WTHHFIN14" "WTHHFIN15" "WTHHFIN16" "WTHHFIN17" "WTHHFIN18" "WTHHFIN19" "WTHHFIN20" "WTHHFIN21" "WTHHFIN22"
 [25] "WTHHFIN23" "WTHHFIN24" "WTHHFIN25" "WTHHFIN26" "WTHHFIN27" "WTHHFIN28" "WTHHFIN29" "WTHHFIN30" "WTHHFIN31" "WTHHFIN32" "WTHHFIN33" "WTHHFIN34"
 [37] "WTHHFIN35" "WTHHFIN36" "WTHHFIN37" "WTHHFIN38" "WTHHFIN39" "WTHHFIN40" "WTHHFIN41" "WTHHFIN42" "WTHHFIN43" "WTHHFIN44" "WTHHFIN45" "WTHHFIN46"
 [49] "WTHHFIN47" "WTHHFIN48" "WTHHFIN49" "WTHHFIN50" "WTHHFIN51" "WTHHFIN52" "WTHHFIN53" "WTHHFIN54" "WTHHFIN55" "WTHHFIN56" "WTHHFIN57" "WTHHFIN58"
 [61] "WTHHFIN59" "WTHHFIN60" "WTHHFIN61" "WTHHFIN62" "WTHHFIN63" "WTHHFIN64" "WTHHFIN65" "WTHHFIN66" "WTHHFIN67" "WTHHFIN68" "WTHHFIN69" "WTHHFIN70"
 [73] "WTHHFIN71" "WTHHFIN72" "WTHHFIN73" "WTHHFIN74" "WTHHFIN75" "WTHHFIN76" "WTHHFIN77" "WTHHFIN78" "WTHHFIN79" "WTHHFIN80" "WTHHFIN81" "WTHHFIN82"
 [85] "WTHHFIN83" "WTHHFIN84" "WTHHFIN85" "WTHHFIN86" "WTHHFIN87" "WTHHFIN88" "WTHHFIN89" "WTHHFIN90" "WTHHFIN91" "WTHHFIN92" "WTHHFIN93" "WTHHFIN94"
 [97] "WTHHFIN95" "WTHHFIN96" "WTHHFIN97" "WTHHFIN98"

$person
  [1] "HOUSEID"    "PERSONID"   "WTPERFIN"   "WTPERFIN1"  "WTPERFIN2"  "WTPERFIN3"  "WTPERFIN4"  "WTPERFIN5"  "WTPERFIN6"  "WTPERFIN7"  "WTPERFIN8" 
 [12] "WTPERFIN9"  "WTPERFIN10" "WTPERFIN11" "WTPERFIN12" "WTPERFIN13" "WTPERFIN14" "WTPERFIN15" "WTPERFIN16" "WTPERFIN17" "WTPERFIN18" "WTPERFIN19"
 [23] "WTPERFIN20" "WTPERFIN21" "WTPERFIN22" "WTPERFIN23" "WTPERFIN24" "WTPERFIN25" "WTPERFIN26" "WTPERFIN27" "WTPERFIN28" "WTPERFIN29" "WTPERFIN30"
 [34] "WTPERFIN31" "WTPERFIN32" "WTPERFIN33" "WTPERFIN34" "WTPERFIN35" "WTPERFIN36" "WTPERFIN37" "WTPERFIN38" "WTPERFIN39" "WTPERFIN40" "WTPERFIN41"
 [45] "WTPERFIN42" "WTPERFIN43" "WTPERFIN44" "WTPERFIN45" "WTPERFIN46" "WTPERFIN47" "WTPERFIN48" "WTPERFIN49" "WTPERFIN50" "WTPERFIN51" "WTPERFIN52"
 [56] "WTPERFIN53" "WTPERFIN54" "WTPERFIN55" "WTPERFIN56" "WTPERFIN57" "WTPERFIN58" "WTPERFIN59" "WTPERFIN60" "WTPERFIN61" "WTPERFIN62" "WTPERFIN63"
 [67] "WTPERFIN64" "WTPERFIN65" "WTPERFIN66" "WTPERFIN67" "WTPERFIN68" "WTPERFIN69" "WTPERFIN70" "WTPERFIN71" "WTPERFIN72" "WTPERFIN73" "WTPERFIN74"
 [78] "WTPERFIN75" "WTPERFIN76" "WTPERFIN77" "WTPERFIN78" "WTPERFIN79" "WTPERFIN80" "WTPERFIN81" "WTPERFIN82" "WTPERFIN83" "WTPERFIN84" "WTPERFIN85"
 [89] "WTPERFIN86" "WTPERFIN87" "WTPERFIN88" "WTPERFIN89" "WTPERFIN90" "WTPERFIN91" "WTPERFIN92" "WTPERFIN93" "WTPERFIN94" "WTPERFIN95" "WTPERFIN96"
[100] "WTPERFIN97" "WTPERFIN98"

$trip_keys
[1] "HOUSEID"  "PERSONID" "TDTRPNUM" "VEHID"   

> lapply(nhts_data$data, colnames)
$trip
  [1] "HOUSEID"    "PERSONID"   "TDTRPNUM"   "VEHID"      "DROP_PRK"   "DRVR_FLG"   "DWELTIME"   "ENDAMPM"    "ENDHOUR"    "ENDMINTE"   "ENDTIME"   
 [12] "ENDTIME17"  "HHMEMDRV"   "HH_ONTD"    "HOWFRPOS"   "HOWPUBOS"   "LOCNO"      "LOOP_TRIP"  "NONHHCNT"   "NUMONTRP"   "NUMTRANS"   "O_LOCNO"   
 [23] "ONTD_P1"    "ONTD_P10"   "ONTD_P11"   "ONTD_P12"   "ONTD_P13"   "ONTD_P14"   "ONTD_P15"   "ONTD_P2"    "ONTD_P3"    "ONTD_P4"    "ONTD_P5"   
 [34] "ONTD_P6"    "ONTD_P7"    "ONTD_P8"    "ONTD_P9"    "PSGR_FLG"   "PUB_REASON" "PUBTRANS"   "STRTAMPM"   "STRTHR"     "STRTMIN"    "STRTTIME"  
 [45] "STRTTIME17" "TDWKND"     "TRACC1"     "TRACC10"    "TRACC11"    "TRACC12"    "TRACC13"    "TRACC14"    "TRACC15"    "TRACC16"    "TRACC17"   
 [56] "TRACC18"    "TRACC19"    "TRACC2"     "TRACC20"    "TRACC3"     "TRACC4"     "TRACC5"     "TRACC6"     "TRACC7"     "TRACC8"     "TRACC9"    
 [67] "TRACCDK"    "TRACC_O"    "TRACCRF"    "TRACCTM"    "TREGR1"     "TREGR10"    "TREGR11"    "TREGR12"    "TREGR13"    "TREGR14"    "TREGR15"   
 [78] "TREGR16"    "TREGR17"    "TREGR18"    "TREGR19"    "TREGR2"     "TREGR20"    "TREGR3"     "TREGR4"     "TREGR5"     "TREGR6"     "TREGR7"    
 [89] "TREGR8"     "TREGR9"     "TREGRDK"    "TREGR_O"    "TREGRRF"    "TREGRTM"    "TRIPPURP"   "TRPACCMP"   "TRPHHACC"   "TRPHHVEH"   "TRPMILES"  
[100] "TRPMILES17" "TRPPUB"     "TRPTRANS"   "TRPTRANS17" "TRPTRNOS"   "TRVLCMIN"   "TRWAITTM"   "VMT_MILE"   "VMT_MILE17" "WHODROVE"   "WHYFROM"   
[111] "WHYFROM_O"  "WHYTO"      "WHYTRP1S"   "WHYTRP90"   "WHYTRPSP"   "WKBK_DIST"  "WKBK_UNIT" 

$person
  [1] "HOUSEID"    "PERSONID"   "AGERANGE"   "ALT_1"      "ALT_2"      "ALT_3"      "ALT_4"      "ALT_5"      "ALT_6"      "ALT_7"      "ALT_DK"    
 [12] "ALT_O"      "ALT_RF"     "ALT_SE"     "AWAYHOME"   "AWAYHOME17" "BIKE4EX"    "BIKE_D"     "BIKE_DK"    "BIKE_F"     "BIKE_G"     "BIKE_K"    
 [23] "BIKE_P"     "BIKE_R"     "BIKE_RF"    "BIKESHARE"  "BIKE_Z"     "BORNINUS"   "CARRODE"    "CARSHARE"   "CNTTDTR"    "CONDDK"     "CONDNIGH"  
 [34] "CONDNONE"   "CONDPUB"    "CONDRF"     "CONDRIDE"   "CONDRIVE"   "CONDSPEC"   "CONDTAX"    "CONDTRAV"   "DELIVER"    "DIARY"      "DIARYCMP"  
 [45] "DIARYHAV"   "DISTTOSC17" "DISTTOWK17" "DRIVER"     "DRVR"       "EDUC"       "FLEXTIME"   "FRSTHM"     "FRSTHM17"   "GCDWORK"    "GT1JBLWK"  
 [56] "HEALTH"     "JOBCATOS"   "LPACT"      "LSTTRDAY17" "MCA8_OS"    "MCA8_OTH"   "MCUSED"     "MEDCOND"    "MEDCOND6"   "NBIKETRP"   "NOCONG"    
 [67] "NWALKTRP"   "OCCAT"      "OUTCNTRY"   "OUTOFTWN"   "PAYPROF"    "PERINDT2"   "PHYACT"     "PRMACT"     "PROXY"      "PTUSED"     "PUBTIME"   
 [78] "QC_DAY"     "QC_JOINT"   "QC_LOC"     "QC_LOOP"    "QC_TIME"    "RACE_1"     "RACE_2"     "RACE_3"     "RACE_4"     "RACE_5"     "RACE_DK"   
 [89] "RACE_O"     "RACE_RF"    "RACE_SE"    "R_AGE"      "R_HISP"     "RIDESHARE"  "R_RACE"     "R_RELAT"    "R_RETMODE"  "R_SEX"      "SAMEPLC"   
[100] "SAMEPLC_O"  "SCHTRN1"    "SCHTRN1O"   "SCHTRN2"    "SCHTRN2O"   "SCHTYP"     "TDDRIVER"   "TIMETOWK"   "USEPUBTR"   "USEPUBTR17" "VERYRMIL"  
[111] "VPACT"      "WALK4EX"    "WALK_D"     "WALK_DK"    "WALK_E"     "WALK_F"     "WALK_G"     "WALK_K"     "WALK_Q"     "WALK_RF"    "WALK_Z"    
[122] "W_CANE"     "W_CHAIR"    "W_CRUTCH"   "W_DOG"      "WHOPROXY"   "WKFMHMXX"   "WKFTPT"     "WKRMHM"     "WKSTFIPS"   "W_MTRCHR"   "W_NONE"    
[133] "WORKER"     "WRKAMPM"    "WRK_HOME"   "WRKHR"      "WRKMIN"     "WRKTIME"    "WRKTRANS"   "WRKTRNOS"   "W_SCOOTR"   "W_WHCANE"   "W_WLKR"    
[144] "YEARMIL2"   "YEARMILE"   "YRTOUS"     "YRTOUS2"   

$household
  [1] "HOUSEID"    "AIRPORT"    "BIKE"       "BIKE2SAVE"  "BUS"        "CAR"        "CDIVMSAR"   "CENSUS_D"   "CENSUS_R"   "CNTTDHH"    "DIFFDATE"  
 [12] "DRVRCNT"    "FLAG100"    "GASPRICE"   "HBHTNRNT"   "HBHTNRNT17" "HBPPOPDN"   "HBPPOPDN17" "HBRESDN"    "HBRESDN17"  "HH_CBSA"    "HHFAMINC"  
 [23] "HH_HISP"    "HH_RACE"    "HHRELATD"   "HHRESP"     "HHSIZE"     "HHSTATE"    "HHSTFIPS"   "HHVEHCNT"   "HOMELOC_1"  "HOMELOC_10" "HOMELOC_11"
 [34] "HOMELOC_2"  "HOMELOC_3"  "HOMELOC_4"  "HOMELOC_5"  "HOMELOC_6"  "HOMELOC_7"  "HOMELOC_8"  "HOMELOC_9"  "HOMELOC_DK" "HOMELOC_NA" "HOMELOC_RF"
 [45] "HOMEOWN"    "HOMEOWOS"   "HOMETEN"    "HTEEMPDN"   "HTEEMPDN17" "HTHTNRNT"   "HTHTNRNT17" "HTPPOPDN"   "HTPPOPDN17" "HTRESDN"    "HTRESDN17" 
 [56] "INVEST_1"   "INVEST_10"  "INVEST_2"   "INVEST_3"   "INVEST_4"   "INVEST_5"   "INVEST_6"   "INVEST_7"   "INVEST_8"   "INVEST_9"   "INVEST_DK" 
 [67] "INVEST_NA"  "INVEST_RF"  "LANDLINE"   "LANG"       "LD_DIST"    "LIF_CYC"    "MSACAT"     "MSASIZE"    "NUMADLT"    "ODEVICE"    "ODEVICE_O" 
 [78] "PARA"       "PC"         "PLACE"      "PRICE"      "PTRANS"     "RAIL"       "RECMODE"    "RESP_CNT"   "RETMODE"    "SAMPAREA"   "SAMPSTRAT" 
 [89] "SCRESP"     "SPHONE"     "SPONSCHG"   "SPONSOR"    "TAB"        "TAXI"       "TDAYDAT2"   "TDAYDATE"   "TIMEZONE"   "TOLLTAG"    "TRAIN"     
[100] "TRAVDAY"    "TRIP_CODE"  "URBAN"      "URBANSIZE"  "URBRUR"     "WALK"       "WALK2SAVE"  "WEBUSE17"   "WRKCOUNT"   "YOUNGCHILD"

$vehicle
 [1] "HOUSEID"    "VEHID"      "ANNMILES"   "ESTMILE2"   "ESTMILES"   "FUELTYPE"   "FUELTYPE_O" "HFUEL"      "HFUEL_O"    "HYBRID"     "MAKE"      
[12] "MAKE_O"     "MODEL"      "MODEL_O"    "OD_DATE"    "OD_DAY"     "OD_MONTH"   "OD_READ"    "OD_YEAR"    "VEHAGE"     "VEHMILE2"   "VEHMILES"  
[23] "VEHOWNED"   "VEHOWNMO"   "VEHTYOS"    "VEHTYPE"    "VEHYEAR"    "VERESTML"   "VERMILES"   "WHOMAIN"   

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] summarizeNHTS_0.0.0.9000 ggplot2_2.2.1           

loaded via a namespace (and not attached):
 [1] zip_1.0.0           Rcpp_0.12.15        pillar_1.1.0        compiler_3.4.3      plyr_1.8.4          R.methodsS3_1.7.1   R.utils_2.6.0      
 [8] base64enc_0.1-3     tools_3.4.3         digest_0.6.15       uuid_0.1-2          memoise_1.1.0       tibble_1.4.2        gtable_0.2.0       
[15] htmlTable_1.11.2    checkmate_1.8.5     lattice_0.20-35     rlang_0.2.0         rstudioapi_0.7      yaml_2.1.16         rgdal_1.2-16       
[22] withr_2.1.1         officer_0.2.1       stringr_1.3.0       xml2_1.2.0          knitr_1.20          gdtools_0.1.6       htmlwidgets_1.0    
[29] devtools_1.13.5     grid_3.4.3          data.table_1.10.4-3 R6_2.2.2            rvg_0.1.8           ggiraph_0.4.2       sp_1.2-7           
[36] magrittr_1.5        scales_0.5.0        backports_1.1.2     htmltools_0.3.6     colorspace_1.3-2    stringi_1.1.6       lazyeval_0.2.1     
[43] munsell_0.4.3       R.oo_1.21.0

**Comment by dnimish85** [comment] 2018-03-07 20:44
I still believe it is something related to reading csv.

**Comment by AnthonyFucci** [comment] 2018-03-09 15:48
Hm, I don't see anything strange in those outputs. Our outputs match except for a few package versions in the final sessionInfo() call, but I don't suspect that's our problem.

Can you do the instructions in the previous post again where you stated that my solution worked? And carefully document the subsequent steps from that point that then reproduces the error? Document what you did between this step:
```r
library(summarizeNHTS)

prepare_add_on_files(
  directory = "C:/NHTS/INCOG/csv/2017",
  weight_type = "5day"
)
```
And this step (which produces the error you're reporting):
```r
summarize_data(
  data = nhts_data,
  agg = 'person_count'
)
```

Thanks!

**Comment by AnthonyFucci** [comment] 2018-06-20 21:40
I'm going to close this because of how long it's been - please open a new ticket if this issue can be recreated and documented. Thanks!

**Closed as completed by AnthonyFucci** 2018-06-20 21:40 UTC
